### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by berkus** [VoronDesign/Voron-Stealthburner#8] opened 2022-07-25 07:11 UTC
Assembly manual page 42 says "M3 MOUTING BOLTS?"

Should be MOUNTING perhaps.

**Comment by mtaumike** [comment] 2022-07-25 11:38
Mentioned in #2

**Comment by raymondh2** [comment] 2022-07-25 12:55
Duplicate of #2

**Closed by raymondh2** 2022-07-25 12:55 UTC

**Comment by berkus** [comment] 2022-07-26 09:17
Ugh, didn't see that one, sorry!
